import pandas as pd
import json
import os

# Material data based on BMTPC and typical Indian construction practices
# Sources: BMTPC, CPWD, Thermal Properties of Building Materials Technical Document
MATERIALS_DATA = [
    # --- Walls: Masonry & Blocks (20 items) ---
    {"id": "wall_aac_150", "name": "AAC Block Wall (150mm)", "component_type": "wall", "u_value": 0.95, "conductivity": 0.16, "density": 600, "specific_heat": 1000, "thickness": 150, "source_citation": "BMTPC Guide", "official_ref": "BEE ECBC 2017", "source_url": "https://www.bmtpc.org/"},
    {"id": "wall_aac_200", "name": "AAC Block Wall (200mm)", "component_type": "wall", "u_value": 0.81, "conductivity": 0.16, "density": 600, "specific_heat": 1000, "thickness": 200, "source_citation": "BMTPC Guide", "official_ref": "BEE ECBC 2017", "source_url": "https://www.bmtpc.org/"},
    {"id": "wall_aac_250", "name": "AAC Block Wall (250mm)", "component_type": "wall", "u_value": 0.65, "conductivity": 0.16, "density": 600, "specific_heat": 1000, "thickness": 250, "source_citation": "BMTPC Guide", "official_ref": "BEE ECBC 2017", "source_url": "https://www.bmtpc.org/"},
    {"id": "wall_clay_brick_230", "name": "Burnt Clay Brick Wall (230mm)", "component_type": "wall", "u_value": 2.1, "conductivity": 0.81, "density": 1800, "specific_heat": 880, "thickness": 230, "source_citation": "CPWD Rates 2021", "official_ref": "IS 1077", "source_url": "https://cpwd.gov.in/"},
    {"id": "wall_clay_brick_115", "name": "Burnt Clay Brick Wall (115mm)", "component_type": "wall", "u_value": 3.2, "conductivity": 0.81, "density": 1800, "specific_heat": 880, "thickness": 115, "source_citation": "CPWD Rates 2021", "official_ref": "IS 1077", "source_url": "https://cpwd.gov.in/"},
    {"id": "wall_flyash_230", "name": "Fly Ash Brick Wall (230mm)", "component_type": "wall", "u_value": 1.4, "conductivity": 0.5, "density": 1700, "specific_heat": 900, "thickness": 230, "source_citation": "BMTPC Table 2.1", "official_ref": "Green Building Code IND", "source_url": "https://www.bmtpc.org/"},
    {"id": "wall_porotherm_200", "name": "Porotherm Hollow Clay Block (200mm)", "component_type": "wall", "u_value": 1.0, "conductivity": 0.28, "density": 800, "specific_heat": 900, "thickness": 200, "source_citation": "Wienerberger Technical Data", "official_ref": "BEE Approved Alternative", "source_url": "https://www.wienerberger.in/"},
    {"id": "wall_con_block_solid_200", "name": "Solid Concrete Block (200mm)", "component_type": "wall", "u_value": 2.5, "conductivity": 1.2, "density": 2100, "specific_heat": 850, "thickness": 200, "source_citation": "IS 2185 Part 1", "official_ref": "CPWD Specs", "source_url": "https://cpwd.gov.in/"},
    {"id": "wall_con_block_hollow_200", "name": "Hollow Concrete Block (200mm)", "component_type": "wall", "u_value": 1.5, "conductivity": 0.7, "density": 1400, "specific_heat": 850, "thickness": 200, "source_citation": "IS 2185 Part 1", "official_ref": "BEE ECBC 2017", "source_url": "https://cpwd.gov.in/"},
    {"id": "wall_clc_200", "name": "CLC Block Wall (200mm)", "component_type": "wall", "u_value": 0.6, "conductivity": 0.12, "density": 800, "specific_heat": 1000, "thickness": 200, "source_citation": "BMTPC Table 4.3", "official_ref": "BEE ECBC 2017", "source_url": "https://www.bmtpc.org/"},
    {"id": "wall_stabilized_earth", "name": "CSEB Stabilized Earth (230mm)", "component_type": "wall", "u_value": 1.6, "conductivity": 0.75, "density": 1900, "specific_heat": 1050, "thickness": 230, "source_citation": "Auroville Earth Institute", "official_ref": "IS 1725", "source_url": "http://earth-auroville.com/"},
    {"id": "wall_rammed_earth", "name": "Rammed Earth Wall (450mm)", "component_type": "wall", "u_value": 1.0, "conductivity": 0.6, "density": 1900, "specific_heat": 1100, "thickness": 450, "source_citation": "UNESCO Earth Arch", "official_ref": "IGBC Green Homes", "source_url": "http://earth-auroville.com/"},
    {"id": "wall_laterite_300", "name": "Laterite Stone Wall (300mm)", "component_type": "wall", "u_value": 1.8, "conductivity": 0.7, "density": 1600, "specific_heat": 850, "thickness": 300, "source_citation": "BMTPC Traditional", "official_ref": "Vernacular Building Standards", "source_url": "https://www.bmtpc.org/"},
    {"id": "wall_rcc_200", "name": "RCC Wall (200mm)", "component_type": "wall", "u_value": 3.1, "conductivity": 1.58, "density": 2400, "specific_heat": 880, "thickness": 200, "source_citation": "IS 456:2000", "official_ref": "CPWD Specs", "source_url": "https://cpwd.gov.in/"},
    {"id": "wall_rcc_150_ins", "name": "RCC (150mm) + 50mm EPS Insulation", "component_type": "wall", "u_value": 0.55, "conductivity": 0.035, "density": 25, "specific_heat": 1200, "thickness": 200, "source_citation": "BEE Design Guide", "official_ref": "ECBC+ Standard", "source_url": "https://beeindia.gov.in/"},
    {"id": "wall_brick_eps_ins", "name": "Brick (230mm) + 50mm Rockwool", "component_type": "wall", "u_value": 0.48, "conductivity": 0.04, "density": 100, "specific_heat": 840, "thickness": 280, "source_citation": "BEE Design Guide", "official_ref": "Super ECBC", "source_url": "https://beeindia.gov.in/"},
    {"id": "wall_timber_stud_ins", "name": "Timber Stud Wall w/ Fiber Insulation", "component_type": "wall", "u_value": 0.35, "conductivity": 0.04, "density": 500, "specific_heat": 1400, "thickness": 150, "source_citation": "IS 3629:1986", "official_ref": "ECBC User Guide", "source_url": "https://bis.gov.in/"},
    {"id": "wall_ferrocement_50", "name": "Ferro-Cement Panel (50mm)", "component_type": "wall", "u_value": 3.2, "conductivity": 1.0, "density": 2400, "specific_heat": 880, "thickness": 50, "source_citation": "HUDCO Prefab Systems", "official_ref": "CPWD Low Cost", "source_url": "https://hudco.org/"},
    {"id": "wall_puf_panel_100", "name": "PUF Sandwich Panel (100mm)", "component_type": "wall", "u_value": 0.22, "conductivity": 0.022, "density": 40, "specific_heat": 1450, "thickness": 100, "source_citation": "Cold Storage Guide", "official_ref": "BEE Rating", "source_url": "https://tatabluescopesteel.com/"},
    {"id": "wall_eps_core_panel", "name": "Reinforced EPS Core Panel (125mm)", "component_type": "wall", "u_value": 0.42, "conductivity": 0.035, "density": 20, "specific_heat": 1200, "thickness": 125, "source_citation": "BMTPC Prefab Guide", "official_ref": "ECBC Compliant", "source_url": "https://www.bmtpc.org/"},

    # --- Roofs: Slabs & Coatings (15 items) ---
    {"id": "roof_rcc_150", "name": "RCC Slab (150mm) - Standard", "component_type": "roof", "u_value": 3.1, "conductivity": 1.58, "density": 2400, "specific_heat": 880, "thickness": 150, "source_citation": "BMTPC Table 3.5", "official_ref": "IS 456:2000", "source_url": "https://www.bmtpc.org/"},
    {"id": "roof_rcc_ins_50_eps", "name": "RCC (150mm) + 50mm EPS Insulation", "component_type": "roof", "u_value": 0.6, "conductivity": 0.035, "density": 25, "specific_heat": 1200, "thickness": 200, "source_citation": "BEE Guide ECBC 2017", "official_ref": "ECBC Standard", "source_url": "https://beeindia.gov.in/"},
    {"id": "roof_rcc_ins_75_xps", "name": "RCC (150mm) + 75mm XPS Insulation", "component_type": "roof", "u_value": 0.35, "conductivity": 0.03, "density": 35, "specific_heat": 1400, "thickness": 225, "source_citation": "BEE Guide ECBC 2017", "official_ref": "Super ECBC", "source_url": "https://beeindia.gov.in/"},
    {"id": "roof_rcc_ins_100_puf", "name": "RCC (150mm) + 100mm PUF Board", "component_type": "roof", "u_value": 0.2, "conductivity": 0.022, "density": 40, "specific_heat": 1450, "thickness": 250, "source_citation": "BEE Guide ECBC 2017", "official_ref": "Zero Energy Building", "source_url": "https://beeindia.gov.in/"},
    {"id": "roof_cool_white_sri78", "name": "Cool Roof (White Coating SRI 78)", "component_type": "roof", "u_value": 2.8, "conductivity": 1.4, "density": 2300, "specific_heat": 850, "thickness": 155, "source_citation": "CRRC Approved", "official_ref": "TS Cool Roof Policy", "source_url": "https://coolroofs.org/"},
    {"id": "roof_cool_white_sri105", "name": "Cool Roof (High Reflectance SRI 105)", "component_type": "roof", "u_value": 2.7, "conductivity": 1.4, "density": 2300, "specific_heat": 850, "thickness": 155, "source_citation": "CRRC Approved", "official_ref": "BEE Star Rated", "source_url": "https://coolroofs.org/"},
    {"id": "roof_green_extensive", "name": "Green Roof (Extensive - 100mm Soil)", "component_type": "roof", "u_value": 0.5, "conductivity": 0.15, "density": 800, "specific_heat": 1800, "thickness": 250, "source_citation": "NIUA Sustainable Cities", "official_ref": "IGBC Landscape", "source_url": "https://niua.in/"},
    {"id": "roof_green_intensive", "name": "Green Roof (Intensive - 300mm Soil)", "component_type": "roof", "u_value": 0.25, "conductivity": 0.12, "density": 900, "specific_heat": 2000, "thickness": 450, "source_citation": "NIUA Sustainable Cities", "official_ref": "IGBC Landscape", "source_url": "https://niua.in/"},
    {"id": "roof_inverted_pots", "name": "Traditional Inverted Earthen Pots Insulation", "component_type": "roof", "u_value": 1.2, "conductivity": 0.6, "density": 1400, "specific_heat": 1200, "thickness": 250, "source_citation": "Vernacular Passive Cooling", "official_ref": "NIUA Guide", "source_url": "https://niua.in/"},
    {"id": "roof_mangalore_tile", "name": "Mangalore Tiles on Timber Deck", "component_type": "roof", "u_value": 2.4, "conductivity": 0.8, "density": 1800, "specific_heat": 800, "thickness": 40, "source_citation": "BMTPC Traditional", "official_ref": "South India Trad", "source_url": "https://www.bmtpc.org/"},
    {"id": "roof_micro_concrete_tile", "name": "Micro Concrete Roofing (MCR) Tiles", "component_type": "roof", "u_value": 2.8, "conductivity": 1.1, "density": 2000, "specific_heat": 900, "thickness": 20, "source_citation": "TARU Research", "official_ref": "BMTPC Approved", "source_url": "https://www.bmtpc.org/"},
    {"id": "roof_metal_puf_100", "name": "Metal Deck Roof + 100mm PUF", "component_type": "roof", "u_value": 0.21, "conductivity": 0.022, "density": 40, "specific_heat": 1500, "thickness": 105, "source_citation": "BlueScope Data", "official_ref": "BEE Rating", "source_url": "https://tatabluescopesteel.com/"},
    {"id": "roof_asbestos_cement", "name": "Asbestos Cement Sheet (Hazardous/Legacy)", "component_type": "roof", "u_value": 5.2, "conductivity": 0.47, "density": 1500, "specific_heat": 840, "thickness": 6, "source_citation": "Legacy Standards", "official_ref": "Non-Compliant", "source_url": "https://bis.gov.in/"},
    {"id": "roof_thatched", "name": "Traditional Thatched Roof (Thick Grass)", "component_type": "roof", "u_value": 0.85, "conductivity": 0.08, "density": 200, "specific_heat": 1200, "thickness": 150, "source_citation": "HUDCO Rural", "official_ref": "Low Cost Vernacular", "source_url": "https://hudco.org/"},
    {"id": "roof_filler_slab_pots", "name": "Filler Slab (Clay Pot Fillers)", "component_type": "roof", "u_value": 1.8, "conductivity": 0.9, "density": 1600, "specific_heat": 950, "thickness": 150, "source_citation": "COSTFORD Technical", "official_ref": "Sustainable Kerala Style", "source_url": "http://costford.com/"},

    # --- Glazing: Windows & Skylights (15 items) ---
    {"id": "glass_single_clear_6", "name": "Single Clear Glass (6mm)", "component_type": "glazing", "u_value": 5.8, "shgc": 0.82, "conductivity": 1.0, "density": 2500, "specific_heat": 840, "thickness": 6, "source_citation": "Saint-Gobain India", "official_ref": "IGDB v35.0", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_single_tinted_6", "name": "Single Tinted Glass (Green/Bronze 6mm)", "component_type": "glazing", "u_value": 5.7, "shgc": 0.65, "conductivity": 1.0, "density": 2500, "specific_heat": 840, "thickness": 6, "source_citation": "Saint-Gobain India", "official_ref": "BEE ECBC", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_double_clear_6_12_6", "name": "Double Glazed Clear (6/12/6)", "component_type": "glazing", "u_value": 2.8, "shgc": 0.70, "conductivity": 0.03, "density": 2500, "specific_heat": 840, "thickness": 24, "source_citation": "Saint-Gobain India", "official_ref": "IGDB v35.0", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_double_lowe_high", "name": "Double Glazed Low-E (High Perf 6/12/6)", "component_type": "glazing", "u_value": 1.8, "shgc": 0.40, "conductivity": 0.024, "density": 1.2, "specific_heat": 1000, "thickness": 24, "source_citation": "Saint-Gobain India", "official_ref": "ECBC+ Standard", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_double_lowe_super", "name": "Double Glazed Low-E (Super XL 6/12/6)", "component_type": "glazing", "u_value": 1.4, "shgc": 0.25, "conductivity": 0.02, "density": 1.2, "specific_heat": 1000, "thickness": 24, "source_citation": "Saint-Gobain India", "official_ref": "Super ECBC", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_double_tinted_green", "name": "Double Glazed Tinted (Green 6/12/6)", "component_type": "glazing", "u_value": 2.7, "shgc": 0.35, "conductivity": 0.03, "density": 2500, "specific_heat": 840, "thickness": 24, "source_citation": "Saint-Gobain India", "official_ref": "BEE ECBC", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_double_reflective", "name": "Reflective High Performance (ST 167)", "component_type": "glazing", "u_value": 1.6, "shgc": 0.22, "conductivity": 0.02, "density": 2500, "specific_heat": 840, "thickness": 24, "source_citation": "Saint-Gobain SGG Cool-Lite", "official_ref": "Super ECBC Compliant", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_triple_argon", "name": "Triple Glazed Argon (6/12/6/12/6)", "component_type": "glazing", "u_value": 0.8, "shgc": 0.30, "conductivity": 0.016, "density": 2.5, "specific_heat": 1000, "thickness": 42, "source_citation": "Saint-Gobain Advanced", "official_ref": "Zero Energy Building", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_polycarb_10", "name": "Polycarbonate Multiwall (10mm)", "component_type": "glazing", "u_value": 2.5, "shgc": 0.65, "conductivity": 0.21, "density": 1200, "specific_heat": 1200, "thickness": 10, "source_citation": "Sabic Datasheet", "official_ref": "CPWD Skylight", "source_url": "https://www.sabic.com/"},
    {"id": "glass_polycarb_16", "name": "Polycarbonate Multiwall (16mm)", "component_type": "glazing", "u_value": 2.0, "shgc": 0.60, "conductivity": 0.20, "density": 1200, "specific_heat": 1200, "thickness": 16, "source_citation": "Sabic Datasheet", "official_ref": "CPWD Skylight", "source_url": "https://www.sabic.com/"},
    {"id": "glass_dgu_argon_lowe", "name": "DGU Argon Filled Low-E (High Solar)", "component_type": "glazing", "u_value": 1.5, "shgc": 0.55, "conductivity": 0.018, "density": 1.8, "specific_heat": 950, "thickness": 24, "source_citation": "Saint-Gobain India", "official_ref": "Commercial Premium", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_vdf_glazing", "name": "Vacuum Dewired Fire-Rated Glazing", "component_type": "glazing", "u_value": 1.2, "shgc": 0.45, "conductivity": 0.015, "density": 2.0, "specific_heat": 900, "thickness": 20, "source_citation": "Specialist Glass India", "official_ref": "Safety Standard IS 16945", "source_url": "https://in.saint-gobain-glass.com/"},
    {"id": "glass_electrochromic", "name": "Electrochromic Smart Glass (Active State)", "component_type": "glazing", "u_value": 1.1, "shgc": 0.09, "conductivity": 0.012, "density": 2.5, "specific_heat": 850, "thickness": 24, "source_citation": "SageGlass India", "official_ref": "Advanced Adaptive", "source_url": "https://www.sageglass.com/"},
    {"id": "glass_u_profile", "name": "U-Profile Glass (Translucent)", "component_type": "glazing", "u_value": 2.1, "shgc": 0.50, "conductivity": 0.8, "density": 2500, "specific_heat": 840, "thickness": 7, "source_citation": "Pilkington Profilit", "official_ref": "Design Aesthetics", "source_url": "https://www.pilkington.com/"},
    {"id": "glass_safety_laminated", "name": "Laminated Safety Glass (PVB 0.76mm)", "component_type": "glazing", "u_value": 5.4, "shgc": 0.78, "conductivity": 0.9, "density": 2500, "specific_heat": 840, "thickness": 12, "source_citation": "AIS Windows India", "official_ref": "Safety Code", "source_url": "https://www.aiswindows.com/"}
]

def seed_materials():
    file_path = "data/materials.csv"
    df = pd.DataFrame(MATERIALS_DATA)
    df.to_csv(file_path, index=False)
    print(f"Material database seeded at {file_path}")

if __name__ == "__main__":
    if not os.path.exists("data"):
        os.makedirs("data")
    seed_materials()
